# Generated by Django 5.1.3 on 2024-11-25 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('inicio_semestre', 'Inicio de Semestre'), ('fin_semestre', 'Fin de Semestre'), ('inicio_inscripcion', 'Inicio de Inscripción de Asignaturas'), ('fin_inscripcion', 'Fin de Inscripción de Asignaturas'), ('receso', 'Receso Académico'), ('feriado_nacional', 'Feriado Nacional'), ('feriado_regional', 'Feriado Regional'), ('inicio_solicitudes', 'Inicio de Plazos de Solicitudes Administrativas'), ('fin_solicitudes', 'Fin de Plazos de Solicitudes Administrativas'), ('inicio_beneficios', 'Inicio de Plazos para la Gestión de Beneficios'), ('fin_beneficios', 'Fin de Plazos para la Gestión de Beneficios'), ('ceremonia_titulacion', 'Ceremonia de Titulación o Graduación'), ('reunion_consejo', 'Reunión de Consejo Académico'), ('taller_charla', 'Talleres y Charlas'), ('orientacion', 'Día de Orientación para Nuevos Estudiantes'), ('extracurricular', 'Eventos Extracurriculares'), ('inicio_clases', 'Inicio de Clases'), ('ultimo_dia_clases', 'Último Día de Clases'), ('puertas_abiertas', 'Día de Puertas Abiertas'), ('suspension_completa', 'Suspensión de Actividades Completa'), ('suspension_parcial', 'Suspensión de Actividades Parcial')], max_length=30)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='eventos.evento')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
