# Generated by Django 5.1.3 on 2024-11-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Puede gestionar usuarios'), ('can_manage_events', 'Puede gestionar eventos')]},
        ),
    ]
